/*
 * headscale/v1/headscale.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package headscale_api_client

import (
	"time"
)

type V1PreAuthKey struct {
	User       string    `json:"user,omitempty"`
	Id         string    `json:"id,omitempty"`
	Key        string    `json:"key,omitempty"`
	Reusable   bool      `json:"reusable,omitempty"`
	Ephemeral  bool      `json:"ephemeral,omitempty"`
	Used       bool      `json:"used,omitempty"`
	Expiration time.Time `json:"expiration,omitempty"`
	CreatedAt  time.Time `json:"createdAt,omitempty"`
	AclTags    []string  `json:"aclTags,omitempty"`
}
