/*
 * headscale/v1/headscale.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package headscale_api_client

type V1DebugCreateMachineRequest struct {
	User   string   `json:"user,omitempty"`
	Key    string   `json:"key,omitempty"`
	Name   string   `json:"name,omitempty"`
	Routes []string `json:"routes,omitempty"`
}
