/*
 * headscale/v1/headscale.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package headscale_api_client

import (
	"time"
)

type V1ApiKey struct {
	Id         string    `json:"id,omitempty"`
	Prefix     string    `json:"prefix,omitempty"`
	Expiration time.Time `json:"expiration,omitempty"`
	CreatedAt  time.Time `json:"createdAt,omitempty"`
	LastSeen   time.Time `json:"lastSeen,omitempty"`
}
