/*
 * headscale/v1/headscale.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package headscale_api_client

import (
	"time"
)

type V1CreatePreAuthKeyRequest struct {
	User       string    `json:"user,omitempty"`
	Reusable   bool      `json:"reusable,omitempty"`
	Ephemeral  bool      `json:"ephemeral,omitempty"`
	Expiration time.Time `json:"expiration,omitempty"`
	AclTags    []string  `json:"aclTags,omitempty"`
}
