/*
 * headscale/v1/headscale.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package headscale_api_client

import (
	"time"
)

type V1Machine struct {
	Id                   string            `json:"id,omitempty"`
	MachineKey           string            `json:"machineKey,omitempty"`
	NodeKey              string            `json:"nodeKey,omitempty"`
	DiscoKey             string            `json:"discoKey,omitempty"`
	IpAddresses          []string          `json:"ipAddresses,omitempty"`
	Name                 string            `json:"name,omitempty"`
	User                 *V1User           `json:"user,omitempty"`
	LastSeen             time.Time         `json:"lastSeen,omitempty"`
	LastSuccessfulUpdate time.Time         `json:"lastSuccessfulUpdate,omitempty"`
	Expiry               time.Time         `json:"expiry,omitempty"`
	PreAuthKey           *V1PreAuthKey     `json:"preAuthKey,omitempty"`
	CreatedAt            time.Time         `json:"createdAt,omitempty"`
	RegisterMethod       *V1RegisterMethod `json:"registerMethod,omitempty"`
	ForcedTags           []string          `json:"forcedTags,omitempty"`
	InvalidTags          []string          `json:"invalidTags,omitempty"`
	ValidTags            []string          `json:"validTags,omitempty"`
	GivenName            string            `json:"givenName,omitempty"`
	Online               bool              `json:"online,omitempty"`
}
