/*
 * headscale/v1/headscale.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package headscale_api_client

type V1ListPreAuthKeysResponse struct {
	PreAuthKeys []V1PreAuthKey `json:"preAuthKeys,omitempty"`
}
